# Generated by Django 4.2.4 on 2023-08-14 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=200, unique=True, verbose_name='URL')),
                ('body', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение (превью)')),
                ('create_date', models.DateField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('published', models.BooleanField(default=False, verbose_name='признак публикации')),
                ('view_count', models.IntegerField(default=0, verbose_name='колличество просмотров')),
            ],
            options={
                'verbose_name': 'блоговая запись',
                'verbose_name_plural': 'блоговые записи',
            },
        ),
    ]
