# Generated by Django 4.2.4 on 2023-08-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('phone_number', models.CharField(max_length=50, verbose_name='телефон')),
                ('message', models.TextField(blank=True, null=True, verbose_name='сообщение')),
            ],
        ),
    ]
