# Generated by Django 4.2.4 on 2023-08-13 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение (превью)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_change',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата последнего изменения'),
        ),
    ]
