# Generated by Django 4.2.4 on 2023-09-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_product_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.CharField(choices=[('опубликовано', 'Published'), ('не опубликовано', 'Not Published')], default='не опубликовано', verbose_name='статус публикации'),
        ),
    ]
